language: php

php:
 - '7.0'

install:
 - composer install

script:
 - vendor/bin/phpunit --coverage-clover=coverage.xml --whitelist lib --bootstrap vendor/autoload.php tests

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
 - git fetch --tags
 - nvm install 8 && nvm use 8
 - npm install
 - npm run semantic-release

branches:
  except:
   - /^v\d+\.\d+\.\d+$/
